name: Release shared workflow and actions

"on":
  push:
    tags:
      - "*"

permissions:
  contents: write
  packages: write
  id-token: write
  actions: read

jobs:

  lint:
    uses: ./.github/workflows/lint.yml

  test-build:
    name: "Test: Run test build workflow"
    uses: ./.github/workflows/test-build.yml
    secrets: inherit

  test-build-SLSA:
    name: "Test: Run test build workflow"
    uses: ./.github/workflows/test-build-SLSA.yml
    secrets: inherit

  release:
    name: Publish release
    needs: [
      lint,
      test-build,
      test-build-SLSA
    ]
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

      - name: "Release: Package release artifacts"
        run: |
          mkdir -p dist
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          tar -czf dist/"${REPO_NAME}".tar.gz \
            --exclude='.github/workflows/test-*' \
            --exclude='.github/workflows/release.yml' \
            .github

      - name: "Release: Create SHA256SUMS"
        run: |
          cd dist
          LC_ALL=C find . -maxdepth 1 -type f ! -name 'SHA256SUMS*' -print0 | \
            sort -z | \
            xargs -0 sha256sum \
            > SHA256SUMS

      - name: Install Cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad  # v4.0.0

      - name: "Release: Keyless-sign SHA256SUMS"
        run: |
          cd dist
          cosign sign-blob --yes \
            --bundle SHA256SUMS.sigstore.json \
            SHA256SUMS

      - name: "Release: Create GitHub release"
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe  # v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
          files: dist/*
